name: DynmapRailways
version: 1.0.0
main: com.fabianoley.dynmaprailways.DynmapRailways
description: A Dynmap addon for displaying rail lines as a tube map
authors: [FabianoLey]
api-version: "1.21"
softdepend:
  - Dynmap
  - CoreProtect
commands:
  railway:
    description: Railway management commands
    permission: railway.use
permissions:
  railway.use:
    description: Use railway commands
    default: true
  railway.admin:
    description: Administrative railway commands
    default: op
