name: DynmapRailways
version: 1.0.0
main: com.fabianoley.dynmaprailways.DynmapRailways
description: A Dynmap addon for displaying rail lines as a tube map
authors: [FabianoLey]
api-version: "1.21"
depend:
  - dynmap
softdepend:
  - CoreProtect
commands:
  railway:
    description: Railway management commands
    permission: railway.use
permissions:
  railway.use:
    description: Use railway commands
    default: true
  railway.line.personal:
    description: Create and manage personal lines (manual lines and lines you placed)
    default: true
  railway.station:
    description: Create and manage stations
    default: true
  railway.admin:
    description: Administrative railway commands (scan, edit any line, manage everything)
    default: op
    children:
      railway.line.personal: true
      railway.station: true
